version: '3'

services:
  web_server:
    image: 'ivolchenkov/mega-mailer-web-server'
    restart: unless-stopped
    volumes:
      - ./config.yaml:/opt/mega-mailer/config.yaml
    ports:
      - '8000:8000'
  telegram_bot:
    image: 'ivolchenkov/mega-mailer-telegram-bot'
    restart: unless-stopped
    volumes:
      - ./config.yaml:/opt/mega-mailer/config.yaml
  mail_checker:
    image: 'ivolchenkov/mega-mailer-mail-checker'
    restart: unless-stopped
    volumes:
      - ./config.yaml:/opt/mega-mailer/config.yaml
